# Create the sales associate table.
CREATE TABLE SALES_ASSOCIATES(
    ASSOCIATE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME CHAR(30) NOT NULL,
    PASSWORD CHAR(30) NOT NULL,
    SALES_COMMISSION DECIMAL(8, 2) NOT NULL DEFAULT 0,
    ADDRESS CHAR(30)
);

# Create the quotes table.
CREATE TABLE QUOTES(
    QUOTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ASSOCIATE_ID INT NOT NULL,
    PRICE DECIMAL(8, 2),
    STATUS CHAR(30) NOT NULL DEFAULT "Unfinalized", # Can be unfinalized, finalized, sanctioned, or ordered.
    DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CUSTOMER_EMAIL CHAR(100) NOT NULL,
    FOREIGN KEY (ASSOCIATE_ID) REFERENCES SALES_ASSOCIATES(ASSOCIATE_ID)
);

# Create the line items table.
CREATE TABLE LINE_ITEMS(
    QUOTE_ID INT,
    ITEM_NUMBER INT,
    DESCRIPTION CHAR(100) NOT NULL,
    PRICE DECIMAL(8, 2) NOT NULL,
    PRIMARY KEY (QUOTE_ID, ITEM_NUMBER),
    FOREIGN KEY (QUOTE_ID) REFERENCES QUOTES(QUOTE_ID)
);

# Create the secret notes table.
CREATE TABLE SECRET_NOTES(
    QUOTE_ID INT,
    NOTE_NUMBER INT,
    NOTE CHAR(100) NOT NULL,
    PRIMARY KEY (QUOTE_ID, NOTE_NUMBER),
    FOREIGN KEY (QUOTE_ID) REFERENCES QUOTES(QUOTE_ID)
);
